import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { jsPDF } from "jspdf";

const Wizard = () => {
    const navigate = useNavigate();
    const [currentStep, setCurrentStep] = useState(1);
    const totalSteps = 4;

    const [formData, setFormData] = useState({
        personalInfo: {
            fullName: '',
            filingStatus: 'Single',
            dob: '',
            occupation: ''
        },
        income: [],
        deductions: []
    });

    const [errors, setErrors] = useState({});

    const handlePersonalInfoChange = (e) => {
        const { name, value } = e.target;
        setFormData(prev => ({
            ...prev,
            personalInfo: {
                ...prev.personalInfo,
                [name]: value
            }
        }));
        // Clear error
        if (errors[name]) {
            setErrors(prev => ({ ...prev, [name]: null }));
        }
    };

    const handleOptionSelect = (group, value) => {
        if (group === 'filingStatus') {
            setFormData(prev => ({
                ...prev,
                personalInfo: {
                    ...prev.personalInfo,
                    filingStatus: value
                }
            }));
        } else if (group === 'income') {
            setFormData(prev => {
                const newIncome = prev.income.includes(value)
                    ? prev.income.filter(item => item !== value)
                    : [...prev.income, value];
                return { ...prev, income: newIncome };
            });
        } else if (group === 'deductions') {
            setFormData(prev => {
                const newDeductions = prev.deductions.includes(value)
                    ? prev.deductions.filter(item => item !== value)
                    : [...prev.deductions, value];
                return { ...prev, deductions: newDeductions };
            });
        }
    };

    const validateStep = (step) => {
        let isValid = true;
        let newErrors = {};

        if (step === 1) {
            if (!formData.personalInfo.fullName.trim()) {
                newErrors.fullName = 'Please enter your full name.';
                isValid = false;
            }
            if (!formData.personalInfo.dob) {
                newErrors.dob = 'Please select your date of birth.';
                isValid = false;
            }
        }

        setErrors(newErrors);
        return isValid;
    };

    const nextStep = () => {
        if (validateStep(currentStep)) {
            if (currentStep < totalSteps) {
                setCurrentStep(prev => prev + 1);
            } else {
                generatePDF();
            }
        }
    };

    const prevStep = () => {
        if (currentStep > 1) {
            setCurrentStep(prev => prev - 1);
        }
    };

    const generatePDF = () => {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(22);
        doc.setTextColor(22, 101, 52); // Dark Green
        doc.text("NeuralTax AI - 2026 Tax Return Summary", 20, 20);

        // Line
        doc.setLineWidth(0.5);
        doc.setDrawColor(200, 200, 200);
        doc.line(20, 25, 190, 25);

        // Personal Info
        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text("Personal Information", 20, 40);

        doc.setFontSize(12);
        doc.text(`Full Name: ${formData.personalInfo.fullName}`, 20, 50);
        doc.text(`Filing Status: ${formData.personalInfo.filingStatus}`, 20, 60);
        doc.text(`Date of Birth: ${formData.personalInfo.dob}`, 20, 70);
        doc.text(`Occupation: ${formData.personalInfo.occupation || 'N/A'}`, 20, 80);

        // Income
        doc.setFontSize(16);
        doc.text("Income Sources", 20, 100);
        doc.setFontSize(12);
        const incomeText = formData.income.length > 0 ? formData.income.join(', ') : 'None selected';
        doc.text(incomeText, 20, 110);

        // Deductions
        doc.setFontSize(16);
        doc.text("Deductions", 20, 130);
        doc.setFontSize(12);
        const deductionsText = formData.deductions.length > 0 ? formData.deductions.join(', ') : 'None selected';
        doc.text(deductionsText, 20, 140);

        // Summary
        doc.setFillColor(240, 253, 244); // Light Green
        doc.rect(20, 160, 170, 40, 'F');
        doc.setFontSize(14);
        doc.setTextColor(22, 101, 52);
        doc.text("Estimated Federal Refund", 30, 175);
        doc.setFontSize(24);
        doc.text("$2,450.00", 30, 190);

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text("Generated by NeuralTax AI - For estimation purposes only.", 20, 280);

        // Save
        doc.save("NeuralTax_Return_2026.pdf");

        alert("Return filed successfully! Your PDF summary has been downloaded.");
        navigate('/dashboard');
    };

    return (
        <div style={{ background: '#f8fafc', minHeight: '100vh', paddingBottom: '4rem' }}>
            <header style={{ background: 'white', borderBottom: '1px solid #e2e8f0', padding: '1rem 0' }}>
                <div className="container" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', maxWidth: '1200px', margin: '0 auto', padding: '0 2rem' }}>
                    <div className="logo">
                        {/* Assuming logo is in public or imported */}
                        <img src="/neuraltax_logo.png" alt="NeuralTax AI" style={{ height: '30px' }} />
                    </div>
                    <div style={{ fontWeight: 600, color: 'var(--text-secondary)' }}>2026 Tax Return</div>
                    <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
                        <Link to="/" style={{ color: 'var(--text-secondary)', textDecoration: 'none', fontSize: '0.9rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                            <i className="fas fa-home"></i> Home
                        </Link>
                        <Link to="/dashboard" style={{ color: 'var(--text-secondary)', textDecoration: 'none', fontSize: '0.9rem' }}>Save & Exit</Link>
                    </div>
                </div>
            </header>

            <div className="wizard-container" style={{ maxWidth: '800px', margin: '4rem auto', padding: '0 2rem' }}>
                {/* Step Indicator */}
                <div className="step-indicator" style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '3rem', position: 'relative' }}>
                    <div style={{ position: 'absolute', top: '50%', left: 0, width: '100%', height: '2px', background: 'rgba(0, 0, 0, 0.1)', zIndex: 0, transform: 'translateY(-50%)' }}></div>
                    {[1, 2, 3, 4].map(step => (
                        <div key={step} className={`step ${currentStep === step ? 'active' : ''} ${currentStep > step ? 'completed' : ''}`} style={{ position: 'relative', zIndex: 1, background: '#f8fafc', padding: '0 1rem', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.5rem' }}>
                            <div className="step-circle" style={{
                                width: '40px', height: '40px', borderRadius: '50%', background: currentStep > step ? 'var(--bg-dark-deep)' : currentStep === step ? 'var(--accent-green-bright)' : 'white',
                                border: `2px solid ${currentStep > step ? 'var(--bg-dark-deep)' : currentStep === step ? 'var(--accent-green-bright)' : '#ddd'}`,
                                display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 600,
                                color: currentStep > step ? 'var(--accent-green-bright)' : currentStep === step ? 'var(--bg-dark-deep)' : 'var(--text-secondary)',
                                transition: 'all 0.3s ease',
                                boxShadow: currentStep === step ? '0 0 15px rgba(74, 222, 128, 0.4)' : 'none'
                            }}>
                                {currentStep > step ? '✓' : step}
                            </div>
                            <div className="step-label" style={{ fontSize: '0.85rem', color: currentStep === step ? 'var(--bg-dark-deep)' : 'var(--text-secondary)', fontWeight: currentStep === step ? 700 : 500 }}>
                                {step === 1 ? 'Personal Info' : step === 2 ? 'Income' : step === 3 ? 'Deductions' : 'Review'}
                            </div>
                        </div>
                    ))}
                </div>

                <div className="wizard-card" style={{ background: 'white', borderRadius: 'var(--border-radius)', padding: '3rem', boxShadow: '0 10px 30px rgba(0, 0, 0, 0.05)', border: '1px solid rgba(0, 0, 0, 0.05)' }}>
                    {/* Step 1: Personal Info */}
                    {currentStep === 1 && (
                        <div className="wizard-step-content active">
                            <h2 style={{ marginBottom: '0.5rem' }}>Let's start with the basics</h2>
                            <p style={{ color: 'var(--text-secondary)', marginBottom: '2rem' }}>We need some personal information to identify your return.</p>

                            <div className="form-group" style={{ marginBottom: '1.5rem' }}>
                                <label className="form-label" style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 500, color: 'var(--text-dark)' }}>Full Name</label>
                                <input
                                    type="text"
                                    className={`form-input ${errors.fullName ? 'error' : ''}`}
                                    name="fullName"
                                    value={formData.personalInfo.fullName}
                                    onChange={handlePersonalInfoChange}
                                    placeholder="e.g. Jane Doe"
                                    style={{ width: '100%', padding: '0.75rem 1rem', border: `1px solid ${errors.fullName ? '#ef4444' : '#ddd'}`, borderRadius: '8px', fontSize: '1rem' }}
                                />
                                {errors.fullName && <div className="error-msg" style={{ color: '#ef4444', fontSize: '0.8rem', marginTop: '0.25rem' }}>{errors.fullName}</div>}
                            </div>

                            <div className="option-grid" style={{ marginBottom: '1.5rem', display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '1rem' }}>
                                {['Single', 'Married Filing Jointly'].map(status => (
                                    <div
                                        key={status}
                                        className={`option-card ${formData.personalInfo.filingStatus === status ? 'selected' : ''}`}
                                        onClick={() => handleOptionSelect('filingStatus', status)}
                                        style={{
                                            border: `2px solid ${formData.personalInfo.filingStatus === status ? 'var(--accent-green-bright)' : '#eee'}`,
                                            borderRadius: '12px', padding: '1.5rem', cursor: 'pointer', transition: 'all 0.2s', textAlign: 'center',
                                            background: formData.personalInfo.filingStatus === status ? 'rgba(74, 222, 128, 0.05)' : 'transparent',
                                            boxShadow: formData.personalInfo.filingStatus === status ? '0 4px 12px rgba(74, 222, 128, 0.15)' : 'none'
                                        }}
                                    >
                                        <div style={{ fontSize: '1.5rem', marginBottom: '0.5rem' }}>{status === 'Single' ? '👤' : '👥'}</div>
                                        <div style={{ fontWeight: 600 }}>{status}</div>
                                    </div>
                                ))}
                            </div>

                            <div className="form-group" style={{ marginBottom: '1.5rem' }}>
                                <label className="form-label" style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 500, color: 'var(--text-dark)' }}>Date of Birth</label>
                                <input
                                    type="date"
                                    className={`form-input ${errors.dob ? 'error' : ''}`}
                                    name="dob"
                                    value={formData.personalInfo.dob}
                                    onChange={handlePersonalInfoChange}
                                    style={{ width: '100%', padding: '0.75rem 1rem', border: `1px solid ${errors.dob ? '#ef4444' : '#ddd'}`, borderRadius: '8px', fontSize: '1rem' }}
                                />
                                {errors.dob && <div className="error-msg" style={{ color: '#ef4444', fontSize: '0.8rem', marginTop: '0.25rem' }}>{errors.dob}</div>}
                            </div>

                            <div className="form-group" style={{ marginBottom: '1.5rem' }}>
                                <label className="form-label" style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 500, color: 'var(--text-dark)' }}>Occupation</label>
                                <input
                                    type="text"
                                    className="form-input"
                                    name="occupation"
                                    value={formData.personalInfo.occupation}
                                    onChange={handlePersonalInfoChange}
                                    placeholder="e.g. Software Engineer"
                                    style={{ width: '100%', padding: '0.75rem 1rem', border: '1px solid #ddd', borderRadius: '8px', fontSize: '1rem' }}
                                />
                            </div>
                        </div>
                    )}

                    {/* Step 2: Income */}
                    {currentStep === 2 && (
                        <div className="wizard-step-content active">
                            <h2 style={{ marginBottom: '0.5rem' }}>Income Sources</h2>
                            <p style={{ color: 'var(--text-secondary)', marginBottom: '2rem' }}>Select all that apply to you for the 2026 tax year.</p>

                            <div className="option-grid" style={{ display: 'grid', gridTemplateColumns: '1fr', gap: '1rem' }}>
                                {[
                                    { value: 'W-2', icon: '📄', desc: 'Job with a regular paycheck' },
                                    { value: '1099-NEC', icon: '💼', desc: 'Freelance or contract work' },
                                    { value: 'Crypto', icon: '🪙', desc: 'Sold stock, crypto, or other assets' }
                                ].map(item => (
                                    <div
                                        key={item.value}
                                        className={`option-card ${formData.income.includes(item.value) ? 'selected' : ''}`}
                                        onClick={() => handleOptionSelect('income', item.value)}
                                        style={{
                                            border: `2px solid ${formData.income.includes(item.value) ? 'var(--accent-green-bright)' : '#eee'}`,
                                            borderRadius: '12px', padding: '1.5rem', cursor: 'pointer', transition: 'all 0.2s', textAlign: 'left', display: 'flex', alignItems: 'center', gap: '1rem',
                                            background: formData.income.includes(item.value) ? 'rgba(74, 222, 128, 0.05)' : 'transparent',
                                            boxShadow: formData.income.includes(item.value) ? '0 4px 12px rgba(74, 222, 128, 0.15)' : 'none'
                                        }}
                                    >
                                        <div style={{ fontSize: '1.5rem' }}>{item.icon}</div>
                                        <div>
                                            <div style={{ fontWeight: 600 }}>{item.value}</div>
                                            <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>{item.desc}</div>
                                        </div>
                                    </div>
                                ))}
                            </div>

                            <div style={{ marginTop: '2rem', padding: '1rem', background: 'rgba(157, 211, 175, 0.1)', borderRadius: '8px', border: '1px dashed var(--accent-mint)' }}>
                                <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center', marginBottom: '0.5rem' }}>
                                    <span style={{ fontSize: '1.2rem' }}>💡</span>
                                    <span style={{ fontWeight: 600, color: 'var(--bg-dark-deep)' }}>AI Tip</span>
                                </div>
                                <p style={{ fontSize: '0.9rem', color: 'var(--secondary-sage)' }}>You can upload these documents directly in the next step, and I'll extract the data for you.</p>
                            </div>
                        </div>
                    )}

                    {/* Step 3: Deductions */}
                    {currentStep === 3 && (
                        <div className="wizard-step-content active">
                            <h2 style={{ marginBottom: '0.5rem' }}>Maximize Your Refund</h2>
                            <p style={{ color: 'var(--text-secondary)', marginBottom: '2rem' }}>Did you have any of these expenses?</p>

                            <div className="option-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '1rem' }}>
                                {[
                                    { value: 'Student Loan Interest', icon: '🎓' },
                                    { value: 'Mortgage Interest', icon: '🏠' },
                                    { value: 'Medical Expenses', icon: '🏥' },
                                    { value: 'Charitable Donations', icon: '🤲' }
                                ].map(item => (
                                    <div
                                        key={item.value}
                                        className={`option-card ${formData.deductions.includes(item.value) ? 'selected' : ''}`}
                                        onClick={() => handleOptionSelect('deductions', item.value)}
                                        style={{
                                            border: `2px solid ${formData.deductions.includes(item.value) ? 'var(--accent-green-bright)' : '#eee'}`,
                                            borderRadius: '12px', padding: '1.5rem', cursor: 'pointer', transition: 'all 0.2s', textAlign: 'center',
                                            background: formData.deductions.includes(item.value) ? 'rgba(74, 222, 128, 0.05)' : 'transparent',
                                            boxShadow: formData.deductions.includes(item.value) ? '0 4px 12px rgba(74, 222, 128, 0.15)' : 'none'
                                        }}
                                    >
                                        <div style={{ fontSize: '1.5rem', marginBottom: '0.5rem' }}>{item.icon}</div>
                                        <div style={{ fontWeight: 600 }}>{item.value}</div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Step 4: Review */}
                    {currentStep === 4 && (
                        <div className="wizard-step-content active">
                            <h2 style={{ marginBottom: '0.5rem' }}>Review & File</h2>
                            <p style={{ color: 'var(--text-secondary)', marginBottom: '2rem' }}>Here's a summary of your return based on the data provided.</p>

                            <div style={{ background: 'var(--bg-dark-deep)', color: 'white', padding: '2rem', borderRadius: '12px', textAlign: 'center', marginBottom: '2rem' }}>
                                <div style={{ fontSize: '0.9rem', opacity: 0.8, marginBottom: '0.5rem' }}>Estimated Federal Refund</div>
                                <div style={{ fontSize: '3rem', fontWeight: 700, color: 'var(--accent-green-bright)' }}>$2,450</div>
                            </div>

                            <div style={{ border: '1px solid #eee', borderRadius: '8px', overflow: 'hidden' }}>
                                <div style={{ padding: '1rem', background: '#f9fafb', borderBottom: '1px solid #eee', fontWeight: 600 }}>Summary</div>
                                <div style={{ padding: '1rem' }}>
                                    <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                                        <span style={{ color: 'var(--text-secondary)' }}>Name</span>
                                        <span style={{ fontWeight: 600 }}>{formData.personalInfo.fullName || '-'}</span>
                                    </div>
                                    <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                                        <span style={{ color: 'var(--text-secondary)' }}>Filing Status</span>
                                        <span style={{ fontWeight: 600 }}>{formData.personalInfo.filingStatus}</span>
                                    </div>
                                    <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                                        <span style={{ color: 'var(--text-secondary)' }}>Income Sources</span>
                                        <span style={{ fontWeight: 600 }}>{formData.income.length > 0 ? formData.income.join(', ') : 'None'}</span>
                                    </div>
                                    <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                                        <span style={{ color: 'var(--text-secondary)' }}>Deductions</span>
                                        <span style={{ fontWeight: 600 }}>{formData.deductions.length > 0 ? formData.deductions.join(', ') : 'None'}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}

                    <div className="wizard-actions" style={{ display: 'flex', justifyContent: 'space-between', marginTop: '3rem' }}>
                        <button
                            type="button"
                            className="btn"
                            style={{ background: '#eee', color: 'var(--text-dark)', opacity: currentStep === 1 ? 0.5 : 1, cursor: currentStep === 1 ? 'not-allowed' : 'pointer' }}
                            onClick={prevStep}
                            disabled={currentStep === 1}
                        >
                            Back
                        </button>
                        <button
                            type="button"
                            className="btn btn-primary"
                            onClick={nextStep}
                        >
                            {currentStep === totalSteps ? 'File Return' : 'Continue'}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Wizard;
